import Head from 'next/head'
import Tabs from "../components/Tabs";

function SearchPage() {
    return <></>
}

function NormalPage() {
    return
}

export default function Home() {
    const items = [{text: "Hola", route: "/"}, {text: "Como", route: "/"}, {text: "Va", route: "/"}]
    const selected = "Como"
    const query = undefined
    const type = 'creator'

  return (
    <>
      <Head>
        <title>unbiased - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/unbiased-logo-circle.png" />
      </Head>
      {query ? <></> : <Tabs items={items} selected={selected}></Tabs>}
      <div className="d-flex flex-column flex-xl-row ">
          <div className="w-100 w-xl-75 ">

              <Tabs items={items} pill selected={selected}></Tabs>

          </div>
          <div className="card container w-100 w-xl-25 p-4 h-auto m-2 h-fit align-self-xl-start" id="none_shadow">


          </div>
      </div>
    </>
  )
}
