import Head from 'next/head'
import Tabs from "components/Tabs";
import Article from "components/Article";
import Link from "next/link";
import {useAppContext} from "../../context";
import {useRouter} from "next/router";
import CancelSearchLink from "../../components/CancelSearchLink";
import Creator from "../../components/Creator";


export default function SearchPage() {
    const router = useRouter()
    const items = [{text: "Hola", route: "/"}, {text: "Como", route: {
            pathname: '/search',
            query: {...router.query, type: 'creator'}
        }}, {text: "Va", route: "/"}]
    const data = [{id: 1}, {id: 2}]
    const selected = "Hola"
    const ctx = useAppContext()

    const query = router.query.query

  return (
    <>
      <Head>
        <title>unbiased - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/unbiased-logo-circle.png" />
      </Head>
      <div className="d-flex flex-column flex-xl-row ">
          <div className="w-100 w-xl-75 ">
              <Tabs className='my-4' items={items} pill selected={selected}></Tabs>
              <CancelSearchLink text={ctx.I18n("search.filter", [query])}></CancelSearchLink>
              <Tabs items={items} selected={selected}></Tabs>
              <div className="container-fluid">
                  <div className={`row row-cols-md-${router.query.type === 'creator' ? '3' : '2'}`}>
                      {router.query.type === 'creator' ? data.map(d => <Creator key={d.id}></Creator>):
                          data.map(d => <Article key={d.id}></Article>)}
                  </div>

              </div>
          </div>
          <div className="card container w-100 w-xl-25 p-4 h-auto m-2 h-fit align-self-xl-start" id="none_shadow">
          </div>
      </div>
    </>
  )
}
